Bxav\Bundle\ServiceHandlerClientBundle\Entity\SoapService:
    type: entity
    table: soap_service
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        wsdl:
            type: string
            length: 255
            nullable: false
    oneToMany:
        actions:
          targetEntity: SoapAction
          mappedBy: service
