bxav_service_handler_client:
    resource: "@BxavServiceHandlerClientBundle/Resources/config/routing.yml"
    prefix:   /demo

bxav_user:
    resource: "@BxavUserBundle/Resources/config/routing.yml"
    prefix:   /api

bxav_extra_soap_api:
    resource: "@BxavExtraSoapApiBundle/Resources/config/routing.yml"
    prefix:   /api

bxav_service_handler:
    resource: "@BxavServiceHandlerBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin