Bxav\Bundle\UserBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
      customers:
        targetEntity: Customer
        mappedBy: user