Bxav\Bundle\DomainBundle\Entity\DomainCustomer:
    type:  entity
    table: domaincustomer
    repositoryClass: Bxav\Bundle\DomainBundle\Entity\CustomerRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        domain: DomainCustomer
        customer: Bxav\Bundle\UserBundle\Entity\Customer
    fields:
      resellerClubId:
        type: integer
        nullable: true
