services:
    sonata.admin.user:
        class: Bxav\Bundle\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - Bxav\Bundle\UserBundle\Entity\User
            - ~
