bxav_user_manager:
    path:     /user
    defaults: { _controller: bxav_user.controller:serverAction }

bxav_user_manager_wsdl:
    path:     /user/wsdl
    defaults: { _controller: bxav_user.controller:getWsdlAction }

bxav_user_wsdl_dumper:
    path:     /user/dump
    defaults: { _controller: bxav_user.controller:dumperAction }
